### ISSUE TITLE
AMAZING! I cant seem to get the URL scheme to work for me

### ISSUE THREAD

**Issue by zeltak** [simonknittel/obsidian-create-task#20]
Hi and thx so much for your amazing work, been using awful hacks (using apple shortcuts..) to get something similar to your quick capture method, but this seems so much better! :) 

I am pretty bad at programing though (sorry!) and cant seem to get the URL scheme option to work

this works well

```
obsidian://create-task
```
opening the modal input window

yet when I try your example for also putting in the task name

```
obsidian://create-task&task-description=Do%20stuff
```

nothing seem to happen

im sure im missing something right? would you mind giving example code for that?

thx so much!!

**Comment by simonknittel** [comment]
Thank you for the positive feedback @zeltak 

Regarding your issue:
It seems that you are missing the questionmark (`?` )in front of your parameters.

The correct URL would be
```
obsidian://create-task?task-description=Do%20stuff
```
Notice the questionmark (`?`) instead of the ampersand (`&`).

The first parameter must be prepended with a questionmark. All following parameters must be prepended with an ampersand.

**Comment by zeltak** [comment]
that would indeed be great :D
